"""Tag mapping service for English to Chinese tag translation."""

import re
from typing import Dict, List, Optional, Set, Tuple

from app.core.logging_config import get_logger

logger = get_logger(__name__)


class TagMapper:
    """Maps English tags to Chinese tags in the library."""

    def __init__(self):
        """Initialize tag mappings."""
        self.en_to_cn: Dict[str, str] = {}
        self.cn_to_en: Dict[str, str] = {}
        self.chinese_synonyms: Dict[str, List[str]] = {}
        self.blocklist: set[str] = {
            "bra",
            "sex",
            "rape",
            "to",
            "in",
            "or",
            "on",
            "at",
            "is",
            "flat",
            "round",
            "open",
            "close",
            "high",
            "low",
            "wide",
            "narrow",
            "sharp",
            "soft",
            "full",
            "empty",
            "pointy",
            "curvy",
            "round",
            "square",
            "circle",
            "triangle",
            "star",
            "heart",
            "diamond",
        }
        self._build_mappings()

    def _build_mappings(self):
        """Build English to Chinese tag mappings using verified library tags."""
        character_mappings = {
            # Core character types
            "loli": "蘿莉",
            "lolicon": "蘿莉",
            "shota": "正太",
            "shotacon": "正太",
            "milf": "人妻",
            "wife": "人妻",
            "mature": "熟女",
            "mature woman": "熟女",
            "adult woman": "熟女",
            "teen": "少女",
            "teenager": "少女",
            "schoolgirl": "少女",
            "school boy": "少年",
            "catgirl": "貓娘",
            "cat girl": "貓娘",
            "nekomimi": "貓娘",
            "doggirl": "犬娘",
            "dog girl": "犬娘",
            "dog ears": "犬娘",
            "inugami": "犬娘",
            "foxgirl": "狐娘",
            "fox girl": "狐娘",
            "kitsune": "狐娘",
            "kitsune girl": "狐狸娘",
            "elf": "精靈",
            "angel": "天使",
            "demon": "惡魔娘",
            "devil": "惡魔娘",
            "succubus": "魅魔",
            "vampire": "吸血鬼",
            "zombie": "殭屍",
            "mermaid": "人魚",
            "monster": "魔物娘",
            "monster girl": "魔物娘",
            "futanari": "扶他",
            "trap": "偽娘",
            "crossdresser": "偽娘",
            "shemale": "人妖",
            # Extended character types
            "robot": "機器人",
            "mecha": "機娘",
            "maid": "女僕裝",
            "nurse": "護士裝",
            "shrine maiden": "巫女裝",
            "miko": "巫女裝",
            "bunny girl": "兔女郎",
            "fairy": "仙女",
            "ghost": "幽靈",
            "goblin": "哥布林",
            "furry": "福瑞",
            "werewolf": "狼女孩",
            "bat girl": "蝙蝠女",
            "bee girl": "蜂娘",
            "bird girl": "鳥娘",
            "centaur": "半人馬",
            "cow girl": "牛女孩",
            "deer girl": "鹿女孩",
            "horse girl": "馬娘",
            "lizard girl": "蜥蜴娘",
            "spider girl": "蜘蛛娘",
            "snake girl": "蛇娘",
            "slime girl": "史萊姆娘",
            "unicorn": "獨角獸",
            "pegasus": "天馬",
            "mermaid": "美人魚",
            "alien": "外星女",
            "witch": "女巫裝",
            # Anime-specific character types
            "magical girl": "魔法少女",
            "gothic lolita": "歌德蘿莉裝",
            "lolita": "歌德蘿莉裝",
            "onee": "御姐",
            "onee-sama": "御姐",
            "imouto": "義妹",
            "otouto": "義弟",
            "ane": "義姐",
            "oniisan": "義兄",
            "senpai": "學長",
            "kouhai": "學弟",
            "teacher": "教師",
            "coach": "教練",
            "ol": "OL",
            "working woman": "OL",
            "cheerleader": "啦啦隊員",
            "idol": "偶像",
            "ninja": "女忍裝",
            "samurai": "武士",
            "warrior": "戰士",
            "princess": "公主",
            "queen": "女王",
            "maiden": "少女",
            "queen": "女王",
            "loli": "蘿莉",
            "lolicon": "蘿莉",
        }

        clothing_mappings = {
            # Core clothing types
            "school uniform": "女生制服",
            "school_uniform": "女生制服",
            "seifuku": "女生制服",
            "uniform": "女生制服",
            "japanese school uniform": "女生制服",
            "sailor uniform": "女生制服",
            "male uniform": "男生制服",
            "boys uniform": "男生制服",
            "swimsuit": "泳裝",
            "swimwear": "泳裝",
            "bathing suit": "泳裝",
            "school swimsuit": "死庫水",
            "bikini": "比基尼",
            "glasses": "眼鏡",
            "spectacles": "眼鏡",
            "maid outfit": "女僕裝",
            "maid": "女僕裝",
            "french maid": "女僕裝",
            "shrine maiden": "巫女裝",
            "miko": "巫女裝",
            "kimono": "和服",
            "yukata": "浴衣",
            "cheongsam": "旗袍",
            "hanfu": "漢服",
            "bunny girl": "兔女郎",
            "bunny suit": "兔女郎",
            "nurse": "護士裝",
            "nurse outfit": "護士裝",
            "lingerie": "情趣內衣",
            "underwear": "情趣內衣",
            "panties": "內衣",
            "bra": "內衣",
            # Extended clothing types
            "dress": "連身裙",
            "gown": "連身裙",
            "one piece": "連身裙",
            "skirt": "裙子",
            "shorts": "熱褲",
            "hotpants": "熱褲",
            "shirt": "上衣",
            "blouse": "上衣",
            "top": "上衣",
            "pants": "褲子",
            "jeans": "牛仔褲",
            "sweater": "毛衣",
            "hoodie": "連帽衫",
            "jacket": "外套",
            "coat": "外套",
            "blazer": "西裝",
            "suit": "西裝",
            "business suit": "西裝",
            "wedding dress": "婚紗",
            "wedding": "婚紗",
            "cheerleader": "啦啦隊員",
            "sportswear": "運動服",
            "gym uniform": "運動服",
            "track suit": "運動服",
            "gothic lolita": "歌德蘿莉裝",
            "lolita dress": "歌德蘿莉裝",
            "cosplay": "Cosplay",
            "costume": "角色扮演",
            "swimsuit": "泳裝",
            "leotard": "緊身衣",
            "bodysuit": "緊身衣",
            "latex": "乳膠緊身衣",
            "latex suit": "乳膠緊身衣",
            "wetsuit": "濕衣",
            "transparent": "透明服裝",
            "see through": "透明服裝",
            "ninja": "女忍裝",
            "ninja outfit": "女忍裝",
            "samurai armor": "盔甲",
            "armor": "盔甲",
            "military uniform": "軍裝",
            "camouflage": "迷彩",
            "pajamas": "睡衣",
            "sleepwear": "睡衣",
            "lingerie": "情趣內衣",
            "babydoll": "睡裙",
            "bra": "胸罩",
            "pasties": "乳貼",
            "stockings": "長筒襪",
            "thigh highs": "過膝襪",
            "pantyhose": "連褲襪",
            "tights": "連褲襪",
            "socks": "襪子",
            "knee highs": "過膝襪",
            "high heels": "高跟鞋",
            "heels": "高跟鞋",
            "boots": "靴子",
            "knee high boots": "高筒靴",
            "sneakers": "運動鞋",
            "sandals": "涼鞋",
            "flip flops": "拖鞋",
            "slippers": "拖鞋",
            "hat": "帽子",
            "cap": "棒球帽",
            "crown": "王冠",
            "tiara": "寶冠",
            "headband": "頭帶",
            "hairband": "頭帶",
            "ribbon": "蝴蝶結",
            "bow": "蝴蝶結",
            "mask": "面具",
            "eyemask": "眼罩",
            "blindfold": "眼罩",
            "gag": "堵嘴",
            "collar": "項圈",
            "choker": "項圈",
            "necklace": "項鏈",
            "earrings": "耳環",
            "bracelet": "手鐲",
            "ring": "戒指",
            "tie": "領帶",
            "bowtie": "領結",
            "scarf": "圍巾",
            "belt": "腰帶",
            "suspenders": "吊帶",
            "apron": "圍裙",
            "handbag": "手提包",
            "purse": "錢包",
            "backpack": "書包",
            # Additional clothing from tags.json
            "tight shorts": "緊身短褲",
            "bloomers": "燈籠褲",
            "bike shorts": "緊身短褲",
            "gym shorts": "運動短褲",
            "leggings": "緊身褲",
            "pantyhose": "連褲襪",
            "bodystocking": "連身絲襪",
            "catsuit": "緊身衣褲",
            "bandages": "繃帶",
            "dirty": "開洞裝",
            "fishnet": "漁網",
            "fundoshi": "六尺褌",
            "garter belt": "吊襪帶",
            "highleg": "高叉裝",
            "headphones": "頭戴式耳機",
            "scarf": "頭巾",
            "arm gloves": "分隔袖子",
            "diaper": "尿布",
            "training wear": "練功服",
            "miko": "巫女裝",
            "nurse cap": "護士帽",
            "miniskirt": "迷你裙",
            "sundress": "洋裝",
            "sailor": "水手服",
            "t-shirt": "T恤",
            "polo shirt": "POLO衫",
            "tank top": "背心",
            "crop top": "露臍上衣",
            "halter": "細肩帶",
            "strapless": "無肩帶",
            "strap": "肩帶",
            "bowtie": "領結",
            "cravat": "領結",
            "ascot": "領結",
        }

        body_mappings = {
            # Breast size
            "flat chest": "貧乳",
            "small breasts": "貧乳",
            "small boob": "貧乳",
            "tiny breasts": "貧乳",
            "flat": "貧乳",
            "small": "貧乳",
            "tiny": "貧乳",
            "average breasts": "普通乳",
            "medium breasts": "普通乳",
            "large breasts": "巨乳",
            "big breasts": "巨乳",
            "huge breasts": "爆乳",
            "huge_breasts": "巨乳",
            "large_breasts": "巨乳",
            "big boob": "巨乳",
            "big tits": "巨乳",
            "busty": "巨乳",
            "massive breasts": "爆乳",
            "gigantic breasts": "爆乳",
            "big": "巨乳",
            "huge": "爆乳",
            "massive": "爆乳",
            "enormous": "爆乳",
            # Muscle
            "muscle": "肌肉",
            "muscular": "大肌肉",
            "athletic": "肌肉",
            "fit": "肌肉",
            "strong": "肌肉",
            # Hair
            "twintails": "雙馬尾",
            "double tails": "雙馬尾",
            "ponytail": "馬尾",
            "single ponytail": "單馬尾",
            "long hair": "長髮",
            "short hair": "短髮",
            "curly hair": "捲髮",
            "wavy hair": "波浪髮",
            "straight hair": "直髮",
            "braid": "辮子",
            "buns": "丸子頭",
            "bob": "鮑伯頭",
            "pixie cut": "精靈短髮",
            "afro": "爆炸頭",
            # Hair colors
            "blonde": "金髮",
            "yellow hair": "金髮",
            "golden hair": "金髮",
            "red hair": "紅髮",
            "orange hair": "橙髮",
            "blue hair": "藍髮",
            "green hair": "綠髮",
            "purple hair": "紫髮",
            "pink hair": "粉紅髮",
            "white hair": "白髮",
            "silver hair": "銀髮",
            "grey hair": "灰髮",
            "gray hair": "灰髮",
            "black hair": "黑髮",
            "brown hair": "棕髮",
            "auburn hair": "紅棕色",
            # Body features
            "glasses": "眼鏡",
            "spectacles": "眼鏡",
            "contacts": "隱形眼鏡",
            "contact lenses": "隱形眼镜",
            "sunglasses": "太陽鏡",
            "tattoo": "紋身",
            "tattoos": "紋身",
            "ink": "紋身",
            "piercing": "穿孔",
            "nipple piercing": "乳頭穿孔",
            "ear piercing": "耳洞",
            "nose piercing": "鼻環",
            "belly button": "肚臍",
            "navel": "肚臍",
            "wings": "翅膀",
            "tail": "尾巴",
            "cat ears": "貓娘",
            "dog ears": "犬娘",
            "fox ears": "狐娘",
            "animal ears": "獸耳",
            "pointy ears": "精靈",
            "horns": "角",
            "demon horns": "角",
            "halo": "光環",
            "freckles": "雀斑",
            "tan lines": "曬痕",
            "scar": "疤痕",
            "scars": "疤痕",
            "hairy": "多毛",
            "armpit hair": "腋毛",
            "beard": "鬍子",
            "mustache": "鬍子",
            "moustache": "鬍子",
            "eyebrows": "眉毛",
            "thick eyebrows": "濃眉",
            # Additional body features
            "big areola": "大乳暈",
            "inverted nipples": "乳頭內凹",
            "extra nipples": "多乳頭",
            "heterochromia": "異色瞳",
            "different colored eyes": "異色瞳",
            "cross eyed": "鬥雞眼",
            "blind": "失明",
            "one eye": "獨眼",
            "cyclops": "獨眼",
            "big eyes": "大眼睛",
            "small eyes": "小眼睛",
            "droopy eyes": "下垂眼",
            "cat mouth": "貓嘴",
            "thick lips": "厚唇",
            "thin lips": "薄唇",
            "bushy eyebrows": "濃眉",
            "thin eyebrows": "細眉",
            "manicure": "美甲",
            "nail polish": "美甲",
            "mask": "假面",
            "face mask": "口罩",
            "hood": "帽兜",
            "crown": "王冠",
            "tiara": "寶冠",
            "gas mask": "防毒面具",
            "eye mask": "眼部面具",
            "eyepatch": "眼罩",
            "blindfold": "遮掩布",
            "closed eyes": "閉眼",
            "tears": "流淚",
            "crying": "流淚",
            "pupils": "瞳孔",
            "split tongue": "分叉舌",
            "long tongue": "長舌",
            "bite mark": "咬痕",
            "body writing": "身體寫字",
            "body painting": "身體彩繪",
            "calibration marks": "刻度標記",
            "sun tan": "曬痕",
            "skin suit": "人皮衣",
            "skinny": "皮包骨",
            "thin": "皮包骨",
            "obese": "棉花糖女孩",
            "fat": "肥胖",
            "bbw": "肥胖",
            "weight gain": "體重增加",
            "weight loss": "減肥",
            "albino": "白化",
            "dark skin": "黑肉",
            "tan": "黑肉",
            "beauty mark": "美人痣",
            "ahegao": "阿嘿顏",
            "lewd face": "阿嘿顏",
        }

        action_mappings = {
            # Sexual actions
            "oral": "口交",
            "blowjob": "口交",
            "deepthroat": "深喉嚨",
            "face fuck": "顏射",
            "paizuri": "乳交",
            "titfuck": "乳交",
            "breast job": "乳交",
            "anal": "肛交",
            "anal sex": "肛交",
            "sex": "做愛",
            "intercourse": "做愛",
            "vaginal": "陰道交",
            "handjob": "手淫",
            "finger": "指交",
            "fingering": "指交",
            "cunnilingus": "舔陰",
            "rimming": "舔屁眼",
            "footjob": "足交",
            "foot worship": "舔腳",
            "masturbation": "自慰",
            "solo": "自慰",
            "vibrator": "情趣玩具",
            "dildo": "情趣玩具",
            "sex toys": "情趣玩具",
            # Bondage & BDSM
            "bondage": "綁縛",
            "bound": "綁縛",
            "tied": "綁縛",
            "chained": "鐵鏈",
            "shackles": "腳鐐",
            "cuffed": "手銬",
            "handcuffed": "手銬",
            "rope": "繩索",
            "rope bondge": "綑綁",
            "gag": "堵嘴",
            "gagged": "堵嘴",
            "blindfold": "眼罩",
            "blindfolded": "眼罩",
            "collar": "項圈",
            "leash": "牽繩",
            "pet play": "人寵",
            "petplay": "人寵",
            "bdsm": "調教",
            "domination": "支配",
            "dom": "主導",
            "sub": "服從",
            "submissive": "服從",
            "dominant": "主導",
            "sadism": "施虐",
            "masochism": "受虐",
            "cum": "射精",
            "ejaculation": "射精",
            "orgasm": "高潮",
            "multiple orgasm": "連續高潮",
            "squirt": "潮吹",
            "gushing": "潮吹",
            "creampie": "內射",
            "internal": "內射",
            "facial": "顏射",
            "cum on face": "顏射",
            "bodyshot": "顏射",
            "assjob": "屁股交",
            "spanking": "打屁股",
            "wrestling": "摔角",
            "fighting": "戰鬥",
            # Non-sexual actions
            "kissing": "接吻",
            "kiss": "接吻",
            "hugging": "擁抱",
            "hug": "擁抱",
            "holding hands": "牵手",
            "hand holding": "牵手",
            "walking": "走路",
            "running": "跑步",
            "standing": "站立",
            "sitting": "坐下",
            "lying": "躺臥",
            "sleeping": "睡覺",
            "eating": "吃飯",
            "drinking": "喝酒",
            "smoking": "吸菸",
            "crying": "哭泣",
            "smiling": "微笑",
            "laughing": "笑",
            "angry": "生氣",
            "sad": "悲傷",
            "surprised": "驚訝",
            "shy": "害羞",
            "blushing": "臉紅",
            "embarrassed": "尷尬",
            # Group actions
            "threesome": "三人",
            "group": "多人",
            "orgy": "雜交",
            "gangbang": "輪姦",
            "double penetration": "雙重插入",
            "triple penetration": "三重插入",
            # Additional from tags.json
            "tentacles": "觸手",
            "rape": "強姦",
            "non-consensual": "強姦",
            "bestiality": "獸交",
            "animals": "獸交",
            "prostitution": "賣淫",
            "escort": "賣淫",
            "cheating": "出軌",
            "adultery": "出軌",
            "incest": "亂倫",
            "family": "亂倫",
        }

        theme_mappings = {
            # Core themes
            "ntr": "NTR",
            "netorare": "NTR",
            "netorase": "換妻",
            "cuckold": "綠帽癖",
            "yuri": "百合",
            "lesbian": "百合",
            "girl love": "百合",
            "gl": "百合",
            "yaoi": "耽美",
            "boy love": "耽美",
            "bl": "耽美",
            "harem": "後宮",
            "reverse harem": "逆後宮",
            "vanilla": "純愛",
            "pure love": "純愛",
            "romance": "戀愛",
            "romantic": "戀愛",
            "love": "愛情",
            "incest": "亂倫",
            "family": "亂倫",
            "blood relationship": "亂倫",
            "rape": "強姦",
            "non-consensual": "強姦",
            "consensual": "同意",
            "coercion": "強制",
            "force": "強制",
            "mind break": "洗腦",
            "brainwashing": "洗腦",
            "hypnosis": "催眠",
            "training": "調教",
            "slave": "奴隸",
            "slavery": "奴隸",
            "bondage": "綁縛",
            "bdsm": "調教",
            "domination": "支配",
            "submission": "服從",
            "feminization": "女性化",
            "sissification": "女性化",
            # Genre themes
            "action": "戰鬥",
            "adventure": "冒險",
            "comedy": "喜劇",
            "drama": "劇情",
            "fantasy": "奇幻",
            "magic": "魔法",
            "horror": "恐怖",
            "guro": "獵奇",
            "grotesque": "獵奇",
            "mystery": "懸疑",
            "psychological": "心理",
            "sci-fi": "科幻",
            "science fiction": "科幻",
            "slice of life": "日常",
            "daily life": "日常",
            "sports": "運動",
            "music": "音樂",
            "historical": "歷史",
            "mecha": "機戰",
            "super robot": "機戰",
            "isekai": "異世界",
            "other world": "異世界",
            "reincarnation": "轉生",
            "system": "系統",
            "game": "遊戲",
            "gaming": "遊戲",
            # School themes
            "school": "學園",
            "school life": "學園",
            "academy": "學園",
            "college": "大學",
            "university": "大學",
            "high school": "高中",
            "middle school": "初中",
            # Anime-specific themes
            "magical girl": "魔法少女",
            "mahou shoujo": "魔法少女",
            "shoujo": "少女",
            "shounen": "少年",
            "josei": "女性",
            "seinen": "成年",
            "ecchi": "色情",
            "hentai": "變態",
            "furry": "福瑞",
            "yuri": "百合",
            "yaoi": "耽美",
            "shotacon": "正太",
            "lolicon": "蘿莉",
            "trap": "偽娘",
            "gender bender": "性轉換",
            "gender change": "性轉換",
            "transformation": "變身",
            "body swap": "換身",
            "possession": "附身",
            "mind control": "洗腦",
            # Mood themes
            "heartwarming": "治愈",
            "touching": "感人",
            "sad": "悲傷",
            "tragic": "悲劇",
            "happy": "快樂",
            "funny": "搞笑",
            "humor": "搞笑",
            "comedic": "搞笑",
            "cute": "可愛",
            "adorable": "可愛",
            "moe": "萌",
            "cool": "帥氣",
            "stylish": "帥氣",
            "dark": "黑暗",
            "serious": "認真",
            "intense": "激烈",
            # Relationship types
            "couple": "情侶",
            "couples": "情侶",
            "friendship": "友誼",
            "rivalry": "競爭",
            "enemy": "敵人",
            "teacher student": "師生",
            "master disciple": "師徒",
            "boss employee": "上司下屬",
            "childhood friend": "青梅竹馬",
            " childhood friend": "幼馴染",
            "neighbors": "鄰居",
            "roommates": "室友",
            "coworkers": "同事",
            # Plot types
            "plot": "劇情",
            "story": "故事",
            "narrative": "敘事",
            "conquest": "征服",
            "subjugation": "征服",
            "training": "訓練",
            "education": "教育",
            "corruption": "墮落",
            "temptation": "誘惑",
            "seduction": "誘惑",
            "revenge": "復仇",
            "retribution": "報復",
            "punishment": "懲罰",
            "reward": "獎勵",
            "punish": "懲罰",
            "reward": "獎勵",
            # Additional themes
            "healing": "治愈",
            " iyashikei": "治愈",
            "tragically": "悲劇",
            "comedy": "喜劇",
            "drama": "劇情",
            "action": "動作",
            "adventure": "冒險",
            "mystery": "懸疑",
            "horror": "恐怖",
            "supernatural": "超自然",
            "paranormal": "超自然",
            "psychological": "心理",
            "demons": "妖魔",
            "monsters": "怪物",
            "ghosts": "幽靈",
            "spirits": "靈魂",
            "angel": "天使",
            "demon": "惡魔",
            "devil": "惡魔",
            "god": "神",
            "goddess": "女神",
        }

        # 中文同義詞映射 - 用於 tag matching 時的額外匹配
        chinese_synonyms: Dict[str, List[str]] = {
            # Core clothing
            "女生制服": ["學校制服", "校服", "學生制服", "水手服", "制服"],
            "男生制服": ["男生校服", "男制服"],
            "泳裝": ["泳衣", "swimwear", "死庫水"],
            "比基尼": ["bikini", "三點式", "兩件式"],
            "情趣內衣": ["內衣", "性感內衣", "睡衣"],
            "和服": ["和服", "和裝", "浴衣"],
            "浴衣": ["浴衣", "和服"],
            "女僕裝": ["女僕", "maid", "女僕服"],
            "護士裝": ["護士", "護理師", "護士服"],
            "兔女郎": ["兔女", "bunny", "兔耳娘"],
            "巫女裝": ["巫女", "神官", "miko"],
            "旗袍": ["中式禮服", "cheongsam"],
            "運動服": ["運動衣", "體育服", "運動褲"],
            "學校體育服": ["體育服", "運動服"],
            "死庫水": ["學校泳裝", "一體式泳裝"],
            "連身裙": ["連衣裙", "洋裝", "連身衣"],
            "熱褲": ["短褲", "迷你褲"],
            "內衣": ["內褲", "胸罩"],
            "緊身衣": ["緊身服", "体操服"],
            "乳膠緊身衣": ["膠衣", "乳膠"],
            "婚紗": ["婚禮服", "白紗"],
            "西裝": ["西服", "商務服"],
            "啦啦隊員": ["啦啦隊", " cheerleader"],
            "女忍裝": ["忍者", "忍服"],
            "白袍": ["醫師袍", "實驗室大衣"],
            "軍裝": ["軍服", "迷彩服"],
            "聖誕裝": ["聖誕老人", "聖誕服"],
            "空姐服": ["空乘", "機組服"],
            "高筒靴": ["長靴", "過膝靴"],
            "高跟鞋": ["高跟", "細高跟鞋"],
            # Core body features
            "巨乳": ["大胸部", "大奶", "波霸", "爆乳", "巨胸部"],
            "爆乳": ["極乳", "超乳", "巨乳"],
            "貧乳": ["平胸", "小胸部", "洗衣板", "平板"],
            "普通乳": ["普通胸部", "普通大小"],
            "大乳暈": ["大乳暈", "乳暈"],
            "乳頭內凹": ["凹陷乳頭"],
            "多乳頭": ["三乳", "額外乳頭"],
            "眼鏡": ["戴眼鏡", "近視", "框架眼鏡"],
            "隱形眼鏡": ["隱形", "角膜接觸鏡"],
            "長髮": ["長頭髮", "披肩髮"],
            "短髮": ["短頭髮", "鮑伯頭", "bob"],
            "雙馬尾": ["雙辮", "雙馬尾辮", "twintails"],
            "馬尾": ["單馬尾", "馬尾辮", "ponytail"],
            "單馬尾": ["馬尾"],
            "捲髮": ["卷髮", "波浪髮", "curly"],
            "螺旋辮": ["辮子", "麻花辮"],
            "丸子頭": ["髮髻", "包子頭"],
            "超長髮": ["極長髮", "長髮"],
            "長瀏海": ["劉海", "前髮"],
            "金髮": ["金色頭髮", "黃髮", "blonde"],
            "紅髮": ["紅色頭髮", "橙髮"],
            "藍髮": ["藍色頭髮"],
            "白髮": ["白色頭髮", "銀髮", "老師"],
            "黑髮": ["黑色頭髮"],
            "紫髮": ["紫色頭髮"],
            "綠髮": ["綠色頭髮"],
            "銀髮": ["白髮", "銀色頭髮"],
            "肌肉": ["健美", "肌肉男"],
            "大肌肉": ["爆炸肌", "健美"],
            "翅膀": ["羽翼", "天使翅膀", "羽"],
            "尾巴": ["貓尾", "狐尾", "犬尾", "兽尾"],
            "獸耳": ["獸耳娘", "獸耳蘿莉", "cat ears", "animal ears", "貓耳", "犬耳", "狐耳"],
            "角": ["惡魔角", "山羊角"],
            "光環": ["天使光環", "halo"],
            "紋身": ["紋身", "刺青", "tattoo"],
            "雀斑": ["臉雀", "小雀斑"],
            "曬痕": ["曬黑線", "tan lines"],
            "疤痕": ["傷疤", " scar"],
            "多毛": ["濃毛", "體毛多"],
            "腋毛": ["腋下毛"],
            "鬍子": ["鬍鬚", "鬚"],
            # Core character types
            "蘿莉": ["蘿莉塔", "幼女", "小女孩", "lolicon", "loli"],
            "正太": ["正太蘿莉", "美少年", "shota"],
            "少女": ["女生", "女孩", "女子", "姑娘", "小女孩"],
            "少年": ["男生", "男孩", "男子", "小鮮肉"],
            "人妻": ["太太", "已婚女性", "OL", "人妻"],
            "熟女": ["輕熟女", "大姐姐", "輕熟"],
            "御姐": ["姐姐", "大姐姐", "御姐"],
            "貓娘": ["貓耳", "貓咪娘", "cat ears", "貓耳娘", "nekomimi"],
            "犬娘": ["犬耳", "狗娘", "dog ears", "汪娘"],
            "狐娘": ["狐耳", "狐狸娘", "fox ears", "狐狸精"],
            "狐狸娘": ["狐狸精", "狐妖"],
            "精靈": ["精靈耳", "elf ears", "尖耳", "fairy"],
            "天使": ["天使翅膀", "光環", "angel"],
            "惡魔娘": ["惡魔", "魅魔", "demon"],
            "吸血鬼": ["吸血", "vampire", "牙"],
            "魔物娘": ["monster girl", "怪物娘", "魔物"],
            "人魚": ["mermaid", "魚人娘", "美人魚"],
            "龍娘": ["龍女", "dragon girl"],
            "獸人": ["獸人", "furry", "獸"],
            "偽娘": ["偽娘", "男扮女裝", "trap"],
            "扶他": ["futanari", "雙性人", "扶她"],
            "人妖": ["人妖", "shemale", "變性人"],
            "機器人": ["機娘", "robot", "機械"],
            # Core themes
            "純愛": ["戀愛", "愛情", "pure love", "vanilla"],
            "NTR": ["綠帽", "ntr", "netorare", "出軌"],
            "百合": ["GL", "girl love", "lesbian", "蕾絲"],
            "耽美": ["BL", "boy love", "yaoi"],
            "後宮": ["宮鬥", "harem"],
            "學園": ["學校", "校園", "school", "學園"],
            "奴隸": ["奴隸", "slave", "性奴"],
            "調教": ["調教", "training", "BDSM"],
            "戰鬥": ["戰鬥", "戰爭", "action", "打架"],
            "奇幻": [" fantasy", "魔法", "奇幻"],
            "科幻": ["sci-fi", "科幻", "未來"],
            "恐怖": ["恐怖", "horror", "驚悚"],
            "搞笑": ["喜劇", "comedy", "幽默"],
            "溫馨": ["治愈", "heartwarming", "溫暖"],
            "運動": ["運動", "sports", "體育"],
            "音樂": ["音樂", "music"],
            "歷史": ["歷史", "historical"],
            "懸疑": ["懸疑", "mystery"],
            "治愈": ["治愈", "healing", "溫馨"],
            "冒險": ["冒險", "adventure"],
            # Art styles
            "黑白": ["單色", "黑白的", "monochrome"],
            "彩色": ["全彩", "色彩的", "color"],
            "草圖": ["草稿", "草圖", "sketch"],
            "線稿": ["線條", "線稿"],
            "完稿": ["完成稿", "完稿"],
            "厚塗": ["厚涂", "厚塗"],
            "手繪風": ["手繪", "手繪風格"],
            # Additional anime-specific terms
            "魔法少女": ["mahou shoujo", "魔法少女"],
            "異世界": ["isekai", "異世界", "轉生"],
            "轉生": ["轉生", "reincarnation"],
            "系統": ["系統", "system"],
            "無雙": ["無雙", "無敵"],
            # Additional body/skin features
            "曬痕": ["曬黑線", "曬痕"],
            "人皮衣": ["人皮", "皮衣"],
            "皮包骨": ["過瘦", "皮包骨"],
            "棉花糖女孩": ["胖女人", "bbw"],
            "米其林女孩": ["肥胖"],
            "體重增加": ["變胖", "增重"],
            "白化": ["白化病", "albino"],
            "黑肉": ["黝黑", "古銅色"],
            "美人痣": ["痣", "美人痣"],
            "阿嘿顏": ["癡女", "ahegao"],
            # Additional actions
            "接吻": ["親吻", "kiss"],
            "擁抱": ["抱抱", "hug"],
            "牵手": ["拉手", "hand holding"],
            "站立": ["站", "站立的"],
            "坐下": ["坐", "坐著的"],
            "躺臥": ["躺", "躺著的"],
            "奔跑": ["跑", "跑步"],
            "戰鬥": ["打架", "打架", "fight"],
            "羞恥": ["害羞", "羞恥play"],
            "悲傷": ["傷心", "哭泣"],
            "微笑": ["笑", "笑著"],
            "自慰": ["手淫", "masturbation", "自慰"],
            "口交": ["blowjob", "口交", "吹簫"],
            "乳交": ["paizuri", "乳交", "乳"],
            "肛交": ["anal", "肛交"],
            "手淫": ["handjob", "手淫"],
            "足交": ["footjob", "足交", "足"],
            "綁縛": ["bondage", "綁縛", "繩縛"],
            "調教": ["training", "調教", "調教"],
            "凌虐": ["凌虐", "torture"],
            "強制": ["強制", "non-consensual"],
            "輪姦": ["gangbang", "輪姦"],
            "觸手": ["tentacles", "触手"],
            "強姦": ["rape", "強姦", "輪姦"],
            "賣淫": ["prostitution", "賣淫"],
            "出軌": ["外遇", "cheating"],
            "亂倫": ["incest", "近親"],
            # Additional compound tags
            "狐狸娘": ["狐狸精", "狐妖", "狐狸耳朵", "fox girl"],
            "犬娘": ["狗娘", "狗狗娘", "dog girl"],
            "貓娘": ["貓咪娘", "貓耳娘", "cat girl"],
            "人魚": ["mermaid", "魚人娘"],
            "殭屍": ["殭屍娘", "喪屍", "zombie"],
            "魅魔": ["succubus", "性交惡魔"],
            "扶他": ["futanari", "雙性人", "人妖"],
            "魔物娘": ["monster girl", "怪物娘"],
            "獨角獸": ["獨角", "unicorn"],
            "天馬": ["天馬", "pegasus"],
            "仙女": ["fairy", "妖精"],
            "幽靈": ["ghost", "鬼"],
            "哥布林": ["goblin", "地精"],
            "半獸人": ["半獸人", "furry"],
        }

        all_mappings: Dict[str, str] = {}
        all_mappings.update(character_mappings)
        all_mappings.update(clothing_mappings)
        all_mappings.update(body_mappings)
        all_mappings.update(action_mappings)
        all_mappings.update(theme_mappings)

        self.en_to_cn = all_mappings
        self.cn_to_en = {v: k for k, v in all_mappings.items()}

        # Store Chinese synonyms
        self.chinese_synonyms = chinese_synonyms

        logger.info("Built %s tag mappings", len(self.en_to_cn))

    def to_chinese(self, english_tag: str) -> Optional[str]:
        """Convert English tag to Chinese."""
        tag_normalized = english_tag.lower().strip().replace("_", " ")
        if tag_normalized in self.blocklist:
            return None
        if tag_normalized in self.en_to_cn:
            return self.en_to_cn[tag_normalized]
        for en_tag, cn_tag in self.en_to_cn.items():
            if len(en_tag) >= 5 and len(tag_normalized) >= 5:
                if en_tag in tag_normalized or tag_normalized in en_tag:
                    return cn_tag
                    return cn_tag
            # Precise regex match for whole words to avoid sub-word mismatches (e.g. 'cat' in 'category')
            if len(en_tag) >= 3:
                pattern = r"\b" + re.escape(en_tag) + r"\b"
                if re.search(pattern, tag_normalized):
                    return cn_tag
        return None

    def to_english(self, chinese_tag: str) -> Optional[str]:
        """Convert Chinese tag to English."""
        return self.cn_to_en.get(chinese_tag)

    def find_chinese_synonyms(self, tag: str) -> List[str]:
        """Find Chinese synonyms for a given tag."""
        return self.chinese_synonyms.get(tag, [])

    def is_synonym(self, tag1: str, tag2: str) -> bool:
        """Check if two tags are synonyms (including via Chinese mapping)."""
        # Direct check
        if tag1 == tag2:
            return True
        # Check Chinese synonyms
        synonyms1 = self.chinese_synonyms.get(tag1, [])
        if tag2 in synonyms1:
            return True
        synonyms2 = self.chinese_synonyms.get(tag2, [])
        if tag1 in synonyms2:
            return True
        # Check en-cn mapping
        cn1 = self.to_chinese(tag1)
        cn2 = self.to_chinese(tag2)
        if cn1 and cn2 and cn1 == cn2:
            return True
        return False

    def map_keywords(self, keywords: List[str]) -> List[Tuple[str, Optional[str]]]:
        """Map a list of English keywords to Chinese tags."""
        return [(kw, self.to_chinese(kw)) for kw in keywords]

    def get_all_mappings(self) -> Dict[str, str]:
        """Get all English to Chinese mappings."""
        return self.en_to_cn.copy()

    def validate_two_way(self, tag: str) -> Tuple[bool, Optional[str]]:
        """Validate that mapping works both ways (EN->CN->EN).

        Returns (is_valid, round_trip_tag) where round_trip_tag is the
        English tag you'd get if you converted CN->EN after EN->CN.
        """
        # EN -> CN
        cn_tag = self.to_chinese(tag)
        if not cn_tag:
            return False, None

        # CN -> EN
        en_back = self.to_english(cn_tag)
        if not en_back:
            return False, cn_tag

        # Check if we get back the original (case-insensitive)
        if en_back.lower().replace("_", " ") == tag.lower().replace("_", " "):
            return True, en_back

        return False, en_back

    def get_compound_tags(self, tag: str) -> List[str]:
        """Get component tags for compound tags like 狐狸娘 -> [狐狸, 獸耳].

        Useful for boosting confidence when multiple visual features are detected.
        """
        compound_map = {
            "狐狸娘": ["狐狸", "獸耳"],
            "犬娘": ["狗", "獸耳"],
            "貓娘": ["貓", "獸耳"],
            "狐娘": ["狐狸", "獸耳"],
            "人魚": ["魚", "人"],
            "殭屍娘": ["殭屍"],
            "吸血鬼": ["吸血鬼"],
            "惡魔娘": ["惡魔"],
            "魅魔": ["惡魔"],
            "天使": ["天使"],
            "精靈": ["精靈"],
        }
        return compound_map.get(tag, [])


_tag_mapper: Optional[TagMapper] = None


def get_tag_mapper() -> TagMapper:
    """Get or create tag mapper singleton."""
    global _tag_mapper
    if _tag_mapper is None:
        _tag_mapper = TagMapper()
    return _tag_mapper
