"""Tag parsing utilities for VLM responses.

Contains functions to parse and extract tags from VLM analysis responses.
Consolidated from app/services/tag_parser.py and app/services/tag_constants.py.
"""

import logging
import re
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# =============================================================================
# Consolidated Keyword lists for tag categorization
# =============================================================================
# These are the main lists used for parsing and categorization

CHARACTER_KEYWORDS = [
    # English
    "loli",
    "shota",
    "teen",
    "mature",
    "milf",
    "catgirl",
    "doggirl",
    "foxgirl",
    "elf",
    "demon",
    "angel",
    "vampire",
    "boy",
    "girl",
    "student",
    "teacher",
    "maid",
    "nurse",
    "mermaid",
    "monster girl",
    "furry",
    "robot",
    "succubus",
    "goblin",
    "fairy",
    # Chinese - Main character types
    "蘿莉",
    "正太",
    "少女",
    "少年",
    "熟女",
    "人妻",
    "御姐",
    "貓娘",
    "犬娘",
    "狐娘",
    "狐狸娘",
    "精靈",
    "天使",
    "惡魔娘",
    "惡魔",
    "吸血鬼",
    "魔物娘",
    "人魚",
    "美人魚",
    "龍娘",
    "獸人",
    "獸娘",
    "偽娘",
    "扶他",
    "人妖",
    "機器人",
    "機娘",
    "蝙蝠女",
    "蜂娘",
    "鳥娘",
    "半人馬",
    "牛女孩",
    "鹿女孩",
    "馬娘",
    "蜥蜴娘",
    "蛇娘",
    "蜘蛛娘",
    "史萊姆娘",
    "天馬",
    "仙女",
    "幽靈",
    "哥布林",
    "半獸人",
    "猴子女",
    "老鼠娘",
    "兔",
    "貓",
    "狗",
    "狼",
    "熊貓娘",
    "綿羊",
    "山羊",
    # Additional anime-specific character types
    "魔法少女",
    "巫女",
    "修女",
    "女僕",
    "護士",
    "空姐",
    "啦啦隊員",
    "OL",
    "辣妹",
    "辣媽",
    "孕婦",
    "病嬌",
    "青梅竹馬",
    "青梅",
    "天降",
    "幼馴染",
    "同級生",
    "學妹",
    "學姐",
    "老師",
    "鄰居",
    "義妹",
    "義姐",
    "不良少女",
    "不良少年",
    "千金小姐",
    "貧乳",
    "巨乳",
]

CLOTHING_KEYWORDS = [
    # English
    "school_uniform",
    "swimsuit",
    "bikini",
    "lingerie",
    "kimono",
    "yukata",
    "maid_outfit",
    "nurse",
    "police_uniform",
    "bunny_suit",
    "dress",
    "shirt",
    "skirt",
    "panties",
    "bra",
    "uniform",
    "costume",
    "leotard",
    "bodysuit",
    "latex",
    "swimwear",
    "gym uniform",
    "sportswear",
    "casual",
    "business suit",
    "wedding dress",
    "cheongsam",
    "hanfu",
    "cosplay",
    "uniform",
    # Chinese - Main clothing types
    "女生制服",
    "男生制服",
    "泳裝",
    "比基尼",
    "情趣內衣",
    "和服",
    "浴衣",
    "女僕裝",
    "護士裝",
    "警服",
    "兔女郎",
    "連身裙",
    "熱褲",
    "內衣",
    "上衣",
    "旗袍",
    "巫女裝",
    "運動服",
    "學校體育服",
    "死庫水",
    "緊身衣",
    "乳膠緊身衣",
    "婚紗",
    "西裝",
    "啦啦隊員",
    "女忍裝",
    "白袍",
    "軍裝",
    "聖誕裝",
    "空姐服",
    "高筒靴",
    "高跟鞋",
    "圍裙",
    "繃帶",
    "緊身短褲",
    "燈籠褲",
    "連身絲襪",
    "緊身衣褲",
    "Cosplay",
    "異性裝扮",
    "分離袖子",
    "尿布",
    "練功服",
    "開洞裝",
    "漁網",
    "六尺褌",
    "吊襪帶",
    "歌德蘿莉裝",
    "運動短褲",
    "高叉裝",
    "頭戴式耳機",
    "頭巾",
    "女3P",
    "幼兒園服",
    "拘束衣",
    "夏裝",
    "足袋",
    "寶冠",
    "厚連褲襪",
    "透明服裝",
    "男侍者裝",
    "女侍者裝",
    "潮濕裝",
    "女巫裝",
    "小丑",
    "管家",
    "收銀員",
    # Additional common clothing items
    "連褲襪",
    "長筒襪",
    "過膝襪",
    "吊襪帶",
    "乳貼",
    "陰囊袋",
    "條紋內褲",
    "踩腳褲",
    "絲襪",
    "網襪",
]

BODY_KEYWORDS = [
    # English - Main body features
    "flat_chest",
    "small_breasts",
    "large_breasts",
    "huge_breasts",
    "big_breasts",
    "busty",
    "glasses",
    "spectacles",
    "contacts",
    "stockings",
    "pantyhose",
    "knee_high_socks",
    "thigh_highs",
    "tattoo",
    "long_hair",
    "short_hair",
    "twintails",
    "ponytail",
    "curly_hair",
    "blonde",
    "red_hair",
    "blue_hair",
    "white_hair",
    "black_hair",
    "purple_hair",
    "green_hair",
    "silver_hair",
    "pink_hair",
    "orange_hair",
    "grey_hair",
    "curvy",
    "muscle",
    "muscular",
    "wings",
    "tail",
    "ears",
    "cat ears",
    "dog ears",
    "fox ears",
    "animal ears",
    "horns",
    "halo",
    "freckles",
    "tan_lines",
    "scar",
    "hairy",
    "armpit_hair",
    # Chinese - Main body features
    "巨乳",
    "爆乳",
    "貧乳",
    "普通乳",
    "美乳",
    "大乳暈",
    "乳頭內凹",
    "多乳頭",
    "眼鏡",
    "隱形眼鏡",
    "太陽眼鏡",
    "長筒襪",
    "連褲襪",
    "過膝襪",
    "紋身",
    "長髮",
    "短髮",
    "雙馬尾",
    "馬尾",
    "單馬尾",
    "捲髮",
    "螺旋辮",
    "丸子頭",
    "超長髮",
    "長瀏海",
    "金髮",
    "紅髮",
    "藍髮",
    "白髮",
    "黑髮",
    "紫髮",
    "綠髮",
    "銀髮",
    "肌肉",
    "大肌肉",
    "翅膀",
    "尾巴",
    "獸耳",
    "角",
    "光環",
    "雀斑",
    "曬痕",
    "疤痕",
    "多毛",
    "腋毛",
    "鬍子",
    "爆炸頭",
    "禿頭",
    "丸子頭",
    "精靈短髮",
    "馬尾",
    "抓握髮",
    "光頭",
    "長髮",
    # Additional body features from tags.json
    "異色瞳",
    "獨眼",
    "瞳孔",
    "大眼睛",
    "小眼睛",
    "下垂眼",
    "上翹眼",
    "貓嘴",
    "厚唇",
    "薄唇",
    "八字眉",
    "濃眉",
    "細眉",
    "美甲",
    "假面",
    "口罩",
    "帽兜",
    "王冠",
    "寶冠",
    "防毒面具",
    "眼部面具",
    "眼罩",
    "遮掩布",
    "閉眼",
    "流淚",
    "瞳孔",
    "分叉舌",
    "長舌",
    "咬痕",
    "身體寫字",
    "身體彩繪",
    "刻度標記",
    "曬痕",
    "人皮衣",
    "皮包骨",
    "肥胖",
    "棉花糖女孩",
    "米其林女孩",
    "體重增加",
    "減肥",
    "白化",
    "黑肉",
    "美人痣",
    "阿嘿顏",
    "曬痕",
]

ACTION_KEYWORDS = [
    # English
    "sex",
    "oral",
    "paizuri",
    "handjob",
    "anal",
    "bondage",
    "tentacles",
    "rape",
    "prostitution",
    "masturbation",
    "kissing",
    "hugging",
    "holding_hands",
    "walking",
    "running",
    "fighting",
    "blowjob",
    "titfuck",
    "footjob",
    "finger",
    "cunnilingus",
    "rimming",
    "deepthroat",
    "facesitting",
    "missionary",
    "doggy",
    "cowgirl",
    "wheelbarrow",
    "reverse cowgirl",
    "standing",
    "sitting",
    "lying",
    "crouching",
    "spanking",
    "wrestling",
    "choking",
    "strangle",
    "blindfold",
    "cuffed",
    "bound",
    "tied",
    "gag",
    # Chinese - Main action types
    "做愛",
    "口交",
    "乳交",
    "手淫",
    "肛交",
    "綁架",
    "觸手",
    "強姦",
    "賣淫",
    "自慰",
    "接吻",
    "親吻",
    "拥抱",
    "牵手",
    "站立",
    "坐下",
    "躺臥",
    "奔跑",
    "戰鬥",
    "羞恥",
    "悲傷",
    "微笑",
    "哭泣",
    "怒吼",
    "睡覺",
    "吃飯",
    "喝酒",
    "吸菸",
    "綁縛",
    "調教",
    "凌虐",
    "強制",
    "輪姦",
    "足交",
    "舔腳",
    "舔屁眼",
    "舔陰蒂",
    "指交",
    "拳交",
    "打屁股",
    "口交顏",
    "深喉嚨",
    "顏射",
    "內射",
    "潮吹",
    "受精",
    "懷孕",
    "產卵",
    "肛門插入",
    "尿道插入",
    "多重插入",
    "兩屌一洞",
    "三屌一洞",
    "人肉按摩棒",
    "打手槍",
    "多重打手槍",
    "打嗝",
    "嘔吐",
    "吞食",
    "喝水",
    "曬痕",
    "吮吸",
    "吹氣",
    "窒息",
    "電擊",
    "毆打",
    "拷打",
    "踩踏",
    "鞭打",
    "絞刑",
    "殺害",
    "獵奇",
    "墮落",
    "洗腦",
    "催眠",
    "人格排泄",
    "寄生",
    "附身",
    "感官共享",
    "換身",
    "迷藥",
    "藥物",
    "酒醉",
    "性冷淡",
    "道德敗壞",
    "呻吟",
    "嬌喘",
    "喘息",
    "叫床",
    # Additional anime-specific actions
    "壁咚",
    "公主抱",
    "膝枕",
    "摸頭",
    "戳臉",
    "捏臉",
    "背後抱",
    "頭靠肩",
    "拉手",
    "挽臂",
    "依靠",
    "凝視",
    "壁男",
    "偷窺",
    "強吻",
    "咬唇",
    "吐舌",
    "眨眼",
    "wink",
    "石化",
    "變身",
    "巨大化",
    "縮小",
    "換身",
    "附身",
]

THEME_KEYWORDS = [
    # English
    "vanilla",
    "ntr",
    "netorare",
    "incest",
    "yuri",
    "yaoi",
    "harem",
    "school_life",
    "romance",
    "comedy",
    "drama",
    "action",
    "fantasy",
    "horror",
    "mystery",
    "adventure",
    "music",
    "historical",
    "slice_of_life",
    "mecha",
    "sports",
    "supernatural",
    # Chinese - Main theme types
    "純愛",
    "NTR",
    "百合",
    "耽美",
    "後宮",
    "學園",
    "戀愛",
    "喜劇",
    "劇情",
    "戰鬥",
    "幻想",
    "魔法",
    "校園",
    "奴隸",
    "調教",
    "奇幻",
    "科幻",
    "恐怖",
    "搞笑",
    "溫馨",
    "運動",
    "音樂",
    "歷史",
    "懸疑",
    "治愈",
    "冒險",
    "热血",
    "校园",
    "都市",
    "異世界",
    "轉生",
    "系統",
    "無雙",
    "後宮",
    "偽娘",
    "扶他",
    "人妖",
    "BL",
    "GL",
    "ML",
    "NL",
    "精神",
    "肉体",
    "慰灵",
    "复仇",
    "救赎",
    "成长",
    "青春",
    "羁绊",
    "命运",
    "战斗",
    "战争",
    "日常",
    "非日常",
    "梦境",
    "现实",
    "虚拟",
    "游戏",
    "竞技",
]

# =============================================================================
# Stop words - words to filter out when extracting keywords
# Consolidated from tag_constants.py
# =============================================================================

STOP_WORDS = frozenset(
    {
        "indicates",
        "also",
        "translates",
        "translated",
        "scanlated",
        "scanlation",
        "credits",
        "page",
        "numbers",
        "chapter",
        "raws",
        "from",
        "the",
        "and",
        "this",
        "with",
        "that",
        "shows",
        "presents",
        "wearing",
        "appears",
        "seems",
        "likely",
        "could",
        "be",
        "is",
        "are",
        "has",
        "have",
        "contains",
        "analysis",
        "results",
        "based",
        "on",
        "image",
        "manga",
        "cover",
        "showing",
        "holding",
        "setting",
        "quality",
        "style",
        "art",
        "modern",
        "clean",
        "which",
        "there",
        "these",
        "those",
        "for",
        "relevant",
        "detected",
        "suggested",
        "including",
        "tags",
        "here",
        "some",
        "following",
        "choice",
        "visible",
        "seen",
        "character",
        "clothing",
        "body",
        "action",
        "theme",
        "features",
        "details",
        "extracted",
        "background",
        "foreground",
        "looks",
        "possibly",
        "identified",
        "elements",
        "version",
        "update",
        "to",
        "of",
    }
)

# =============================================================================
# Keyword mappings for tag extraction (dict form for recommender)
# Consolidated from tag_constants.py
# =============================================================================

CHAR_KEYWORDS = {
    "loli": ["loli", "young girl", "little girl", "child character", "lolicon", "蘿莉", "幼女"],
    "shota": ["shota", "young boy", "little boy", "正太", "美少年"],
    "teen": ["teen", "teenager", "adolescent", "青少年"],
    "mature": ["mature", "adult woman", "female character", "熟女", "御姐"],
    "milf": ["milf", "人妻", "太太", "已婚女性"],
    "catgirl": ["catgirl", "cat girl", "cat ears", "nekomimi", "貓娘", "貓耳", "獸耳"],
    "doggirl": ["doggirl", "dog girl", "dog ears", "犬娘", "犬耳", "狗女孩"],
    "foxgirl": ["foxgirl", "fox girl", "fox ears", "kitsune", "狐娘", "狐狸娘", "狐耳"],
    "elf": ["elf", "elven", "pointed ears", "精靈", "精靈耳"],
    "demon": ["demon", "succubus", "devil", "horns", "惡魔娘", "惡魔", "魅魔"],
    "angel": ["angel", "angelic", "wings", "halo", "天使", "光環"],
    "vampire": ["vampire", "fangs", "吸血鬼", "牙"],
    "mermaid": ["mermaid", "人魚", "美人魚"],
    "monster": ["monster", "monster girl", "魔物娘", "怪物娘"],
    "robot": ["robot", "機娘", "機器人", "機械"],
    "furry": ["furry", "福瑞", "獸人", "獸娘"],
    "mature_woman": ["熟女", "人妻", "禦姐"],
    "schoolgirl": ["schoolgirl", "女生制服", "校服", "學生"],
    "maid": ["maid", "女僕", "女僕裝"],
    "nurse": ["nurse", "護士", "護士裝"],
    "shrine_maiden": ["shrine maiden", "巫女", "巫女裝"],
    "bunny_girl": ["bunny girl", "兔女郎", "兔耳"],
    # Extended mappings
    "蘿莉": ["蘿莉", "蘿莉塔", "幼女", "小女孩", "低蘿莉"],
    "正太": ["正太", "正太蘿莉", "美少年"],
    "少女": ["少女", "女生", "女孩", "女子", "姑娘"],
    "少年": ["少年", "男生", "男孩", "男子"],
    "人妻": ["人妻", "太太", "已婚女性", "OL"],
    "熟女": ["熟女", "輕熟女", "大姐姐"],
    "禦姐": ["禦姐", "姐姐", "大姐姐"],
    "百合": ["百合", "GL", "girl love", "女同性戀"],
    "耽美": ["耽美", "BL", "boy love", "男同性戀"],
    "NTR": ["NTR", "netorare", "綠帽", "出軌"],
    "純愛": ["純愛", "戀愛", "愛情"],
    "後宮": ["後宮", "宮鬥"],
}

CLOTHING_KEYWORDS_DICT = {
    "school_uniform": [
        "school uniform",
        "seifuku",
        "uniform",
        "女生制服",
        "男生制服",
        "校服",
        "水手服",
    ],
    "swimsuit": ["swimsuit", "swimwear", "bathing suit", "泳裝", "泳衣", "死庫水"],
    "bikini": ["bikini", "比基尼", "三點式"],
    "lingerie": ["lingerie", "underwear", "情趣內衣", "內衣", "睡衣"],
    "kimono": ["kimono", "yukata", "和服", "浴衣"],
    "maid_outfit": ["maid", "maid outfit", "maid dress", "女僕", "女僕裝"],
    "nurse": ["nurse", "nurse outfit", "護士", "護士裝"],
    "police_uniform": ["police", "officer", "警服", "警察"],
    "bunny_suit": ["bunny suit", "bunny girl", "兔女郎", "兔耳"],
    "glasses": ["glasses", "spectacles", "眼鏡"],
    "twintails": ["twintails", "雙馬尾", "雙辮"],
    "ponytail": ["ponytail", "馬尾", "單馬尾"],
    # Extended mappings
    "旗袍": ["旗袍", "cheongsam", "中式禮服"],
    "巫女裝": ["巫女裝", "巫女", "神官", "miko"],
    "兔女郎": ["兔女郎", "兔女", "bunny"],
    "和服": ["和服", "和裝"],
    "運動服": ["運動服", "運動衣", "體育服"],
    "連身裙": ["連身裙", "連衣裙", "洋裝"],
    "比基尼": ["比基尼", "bikini", "三點式"],
    "情趣內衣": ["情趣內衣", "性感內衣"],
    "女僕裝": ["女僕裝", "女僕", "maid"],
    "護士裝": ["護士裝", "護士"],
    "兔女郎": ["兔女郎", "兔女"],
    "熱褲": ["熱褲", "短褲", "bike shorts"],
    "絲襪": ["絲襪", "網襪", "黑絲"],
    "長筒襪": ["長筒襪", "過膝襪", "吊帶襪"],
    "連褲襪": ["連褲襪", "打底襪", "pantyhose"],
    "婚紗": ["婚紗", "婚禮服", "wedding dress"],
    "西裝": ["西裝", "西服", "商務裝"],
    "緊身衣": ["緊身衣", "緊身褲", "leotard"],
    "乳膠緊身衣": ["乳膠緊身衣", "膠衣", "latex"],
}

BODY_KEYWORDS_DICT = {
    "flat_chest": ["flat chest", "small breasts", "貧乳", "平胸", "洗衣板"],
    "small_breasts": ["small breasts", "modest", "貧乳", "小胸部"],
    "large_breasts": ["large breasts", "big breasts", "busty", "巨乳", "大奶", "波霸"],
    "huge_breasts": ["huge breasts", "爆乳", "巨乳"],
    "glasses": ["glasses", "eyewear", "spectacles", "眼鏡", "戴眼鏡"],
    "stockings": ["stockings", "thigh highs", "長筒襪", "過膝襪"],
    "pantyhose": ["pantyhose", "tights", "連褲襪", "打底襪"],
    "knee_high_socks": ["knee high socks", "long socks", "過膝襪"],
    "tattoo": ["tattoo", "ink", "紋身", "紋身"],
    "long_hair": ["long hair", "長髮", "長頭髮"],
    "short_hair": ["short hair", "短髮", "短頭髮", "鮑伯頭"],
    "twintails": ["twintails", "double tails", "雙馬尾", "雙辮"],
    "blonde": ["blonde", "yellow hair", "yellow", "golden hair", "金髮", "金髮"],
    "red_hair": ["red hair", "red", "orange hair", "紅髮", "橙髮"],
    "blue_hair": ["blue hair", "blue", "藍髮"],
    "white_hair": ["white hair", "white", "silver hair", "白髮", "銀髮"],
    "black_hair": ["black hair", "black", "黑髮"],
    "purple_hair": ["purple hair", "purple", "紫髮"],
    "green_hair": ["green hair", "green", "綠髮"],
    "pink_hair": ["pink hair", "pink", "粉紅髮"],
    "wings": ["wings", "翅膀", "羽翼"],
    "tail": ["tail", "尾巴", "狐尾", "貓尾"],
    "ears": ["ears", "耳朵", "獸耳", "貓耳", "犬耳", "狐耳"],
    "horns": ["horns", "角", "惡魔角"],
    "halo": ["halo", "光環"],
    # Extended mappings
    "巨乳": ["巨乳", "大胸部", "大奶", "波霸", "爆乳"],
    "貧乳": ["貧乳", "平胸", "小胸部", "洗衣板"],
    "雙馬尾": ["雙馬尾", "雙辮", "雙馬尾辮"],
    "馬尾": ["馬尾", "單馬尾", "馬尾辮"],
    "長髮": ["長髮", "長頭髮"],
    "短髮": ["短髮", "短頭髮", "鮑伯頭"],
    "眼鏡": ["眼鏡", "戴眼鏡", "近視"],
    "獸耳": ["獸耳", "獸耳娘", "cat ears", "animal ears"],
    "翅膀": ["翅膀", "天使翅膀", "羽翼"],
    "尾巴": ["尾巴", "貓尾", "狐尾", "犬尾"],
    "紋身": ["紋身", "紋身", "刺青"],
    "肌肉": ["肌肉", "大肌肉", "健美"],
    "紋身": ["紋身", "全身紋身"],
    "雀斑": ["雀斑", "臉雀"],
    "曬痕": ["曬痕", "曬黑線"],
    "疤痕": ["疤痕", "傷疤"],
}


# =============================================================================
# Parsing functions
# =============================================================================


def parse_response(text: str) -> Dict[str, Any]:
    """Parse VLM response into structured metadata."""
    result = {
        "description": text,
        "character_types": [],
        "clothing": [],
        "body_features": [],
        "actions": [],
        "themes": [],
        "settings": [],
        "raw_keywords": [],
    }

    try:
        # Handle structured format if present
        content_to_parse = text.lower()
        description_text = text  # Keep original for result

        if "tags:" in content_to_parse:
            parts = re.split(r"tags:", text, flags=re.IGNORECASE)
            if len(parts) >= 2:
                description_text = parts[0].replace("Description:", "").strip()
                tag_part = parts[1]
            else:
                tag_part = text
        else:
            tag_part = text

        result["description"] = description_text

        # Clean up known junk phrases
        junk_phrases = [
            "the image shows",
            "this is a",
            "based on the",
            "analysis indicates",
            "i detected",
            "likely tags",
            "recommendations:",
            "also relevant",
            "here are some tags",
            "the following tags",
            "i suggest",
            "were detected",
            "extracted from",
            "vision analysis",
            "extracted tags",
            "tags detected",
            "description:",
            "tags:",
        ]
        text_clean = tag_part.lower()
        for phrase in junk_phrases:
            text_clean = text_clean.replace(phrase, "")

        # First try to extract tags from comma-separated list or newlines or dots
        raw_tags = re.split(r"[,\n]|\.\s", text_clean)

        tags = []
        junk_words = {
            "also",
            "relevant",
            "detected",
            "suggested",
            "tags",
            "image",
            "manga",
            "cover",
            "vision",
            "analysis",
            "results",
            "showing",
            "with",
            "from",
            "translated",
            "scanlated",
            "credits",
            "chapter",
            "page",
            "raws",
            "version",
            "translates",
            "to",
            "of",
            "and",
            "the",
            "this",
            "that",
            "for",
            "in",
            "on",
            "at",
            "by",
            "as",
            "is",
            "are",
            "was",
            "were",
            "be",
            "been",
            "being",
        }

        for tag in raw_tags:
            # Remove content before colon (e.g., "detected: loli" -> "loli")
            if ":" in tag:
                tag = tag.split(":")[-1]

            clean_tag = tag.strip().strip(".").strip('"').strip("'").lower()
            # Filter rules: increase minimum length to 3 to avoid "to", "of", "2"" etc.
            if (
                clean_tag
                and not clean_tag.isdigit()
                and len(clean_tag) > 2
                and clean_tag not in junk_words
                and not any(jw in clean_tag.split() for jw in junk_words)
                and len(clean_tag.split()) <= 4
            ):
                tags.append(clean_tag)

        # If no tags found this way, try extracting from descriptive text
        if len(tags) < 2:
            logger.info("No comma-separated tags found, extracting from keywords...")
            tags = extract_tags_from_description(text)

        result["raw_keywords"] = tags

        # Categorize tags
        for tag in tags:
            tag_lower = tag.lower()
            if any(kw in tag_lower for kw in CHARACTER_KEYWORDS):
                result["character_types"].append(tag)
            elif any(kw in tag_lower for kw in CLOTHING_KEYWORDS):
                result["clothing"].append(tag)
            elif any(kw in tag_lower for kw in BODY_KEYWORDS):
                result["body_features"].append(tag)
            elif any(kw in tag_lower for kw in ACTION_KEYWORDS):
                result["actions"].append(tag)
            elif any(kw in tag_lower for kw in THEME_KEYWORDS):
                result["themes"].append(tag)

    except Exception as e:
        logger.warning(f"Failed to parse response: {e}")

    return result


def extract_tags_from_description(text: str) -> List[str]:
    """Extract known tags from descriptive text using keyword matching."""
    text_lower = text.lower()
    found_tags = []

    # Simple keyword mapping for extraction - expanded with more variants
    keywords_map = {
        # Character types - English
        "loli": ["loli", "little girl", "child character", "child-like", "lolicon", "young girl"],
        "shota": ["shota", "young boy", "little boy", "正太", "美少年"],
        "catgirl": ["catgirl", "cat ears", "nekomimi", "貓娘", "貓耳", "cat girl"],
        "doggirl": ["doggirl", "dog ears", "犬娘", "犬耳", "dog girl"],
        "foxgirl": ["foxgirl", "fox ears", "kitsune", "狐娘", "狐狸娘", "fox girl"],
        "elf": ["elf", "fairy", "精靈", "pointed ears"],
        "demon": ["demon", "devil", "succubus", "惡魔娘", "魅魔"],
        "angel": ["angel", "wings", "halo", "天使", "光環"],
        "vampire": ["vampire", "fangs", "吸血鬼", "吸血"],
        "mermaid": ["mermaid", "人魚", "美人魚"],
        "monster": ["monster", "monster girl", "魔物娘", "怪物娘"],
        "robot": ["robot", "機娘", "機器人"],
        "furry": ["furry", "福瑞", "獸人"],
        "maid": ["maid", "女僕", "女僕裝"],
        "nurse": ["nurse", "護士", "護士裝"],
        "mature": ["mature", "adult woman", "熟女", "禦姐"],
        "milf": ["milf", "人妻", "太太"],
        # Character types - Chinese
        "蘿莉": ["蘿莉", "蘿莉塔", "幼女", "小女孩"],
        "正太": ["正太", "正太蘿莉", "美少年"],
        "少女": ["少女", "女生", "女孩", "女子"],
        "少年": ["少年", "男生", "男孩"],
        "人妻": ["人妻", "太太", "已婚"],
        "熟女": ["熟女", "輕熟女"],
        "禦姐": ["禦姐", "姐姐"],
        "貓娘": ["貓娘", "貓耳娘"],
        "狐娘": ["狐娘", "狐狸娘"],
        "犬娘": ["犬娘", "狗娘"],
        # Clothing - English
        "school_uniform": ["school uniform", "seifuku", "uniform", "schoolgirl"],
        "swimsuit": ["swimsuit", "swimwear", "泳裝", "泳衣"],
        "bikini": ["bikini", "比基尼"],
        "lingerie": ["lingerie", "underwear", "情趣內衣"],
        "kimono": ["kimono", "和服", "浴衣"],
        "maid_outfit": ["maid", "maid outfit", "女僕裝"],
        "nurse": ["nurse", "nurse outfit", "護士裝"],
        # Clothing - Chinese
        "女生制服": ["女生制服", "校服", "水手服"],
        "男生制服": ["男生制服", "男校服"],
        "泳裝": ["泳裝", "泳衣", "死庫水"],
        "比基尼": ["比基尼", "三點式"],
        "情趣內衣": ["情趣內衣", "性感內衣"],
        "和服": ["和服", "浴衣"],
        "女僕裝": ["女僕裝", "女僕"],
        "護士裝": ["護士裝", "護士"],
        "兔女郎": ["兔女郎", "兔耳"],
        "巫女裝": ["巫女裝", "巫女"],
        "旗袍": ["旗袍", "中式禮服"],
        "運動服": ["運動服", "運動衣"],
        # Body features - English
        "large_breasts": ["large breasts", "busty", "huge breasts", "big breasts", "巨乳", "爆乳"],
        "small_breasts": ["small breasts", "flat chest", "tiny chest", "貧乳", "平胸"],
        "glasses": ["glasses", "spectacles", "眼鏡"],
        "long_hair": ["long hair", "長髮"],
        "short_hair": ["short hair", "短髮"],
        "twintails": ["twintails", "double tails", "雙馬尾"],
        "blonde": ["blonde", "yellow hair", "yellow", "golden hair", "金髮"],
        "blue_hair": ["blue hair", "blue", "藍髮"],
        "pink_hair": ["pink hair", "pink", "粉紅髮"],
        "red_hair": ["red hair", "red", "orange hair", "紅髮"],
        "white_hair": ["white hair", "white", "silver hair", "白髮", "銀髮"],
        "black_hair": ["black hair", "black", "黑髮"],
        "purple_hair": ["purple hair", "purple", "紫髮"],
        "green_hair": ["green hair", "green", "綠髮"],
        # Body features - Chinese
        "巨乳": ["巨乳", "大奶", "波霸"],
        "貧乳": ["貧乳", "平胸"],
        "雙馬尾": ["雙馬尾", "雙辮"],
        "馬尾": ["馬尾", "單馬尾"],
        "長髮": ["長髮"],
        "短髮": ["短髮"],
        "眼鏡": ["眼鏡", "戴眼鏡"],
        "翅膀": ["翅膀", "羽翼"],
        "尾巴": ["尾巴", "貓尾", "狐尾"],
        "獸耳": ["獸耳", "貓耳", "犬耳", "狐耳"],
        # Additional body features
        "肌肉": ["肌肉", "大肌肉", "健美"],
        "紋身": ["紋身", "紋身", "刺青"],
        # Clothing items
        "skirt": ["skirt", "裙子"],
        "dress": ["dress", "gown", "連身裙"],
        "shirt": ["shirt", "blouse", "top", "上衣"],
        "panties": ["panties", "underwear", "內褲"],
        "bra": ["bra", "內衣"],
        "stockings": ["stockings", "socks", "絲襪", "長筒襪"],
        "wings": ["wings", "翅膀"],
        "tail": ["tail", "尾巴"],
        # Themes - English
        "vanilla": ["vanilla", "pure love", "純愛"],
        "ntr": ["ntr", "netorare", "NTR"],
        "yuri": ["yuri", "百合", "GL"],
        "yaoi": ["yaoi", "耽美", "BL"],
        "harem": ["harem", "後宮"],
        # Themes - Chinese
        "純愛": ["純愛", "戀愛"],
        "NTR": ["NTR", "綠帽"],
        "百合": ["百合", "GL"],
        "耽美": ["耽美", "BL"],
        "後宮": ["後宮"],
        "學園": ["學園", "校園"],
    }

    for tag, keywords in keywords_map.items():
        for kw in keywords:
            if kw in text_lower:
                if tag not in found_tags:
                    found_tags.append(tag)
                    logger.info(f"Found tag '{tag}' from keyword '{kw}' in description")
                break
    return found_tags


def extract_tags_from_reasoning(reasoning_text: str) -> List[str]:
    """Extract tags from GLM reasoning content."""
    tags = []

    bullet_pattern = r"[-]\s*([^\n]+)"
    bullets = re.findall(bullet_pattern, reasoning_text)

    for bullet in bullets:
        bullet_clean = bullet.strip().lower()
        if len(bullet_clean) < 50 and not any(
            x in bullet_clean for x in [".", "the ", "this ", "that "]
        ):
            tag = bullet_clean.strip("\"' -")
            if tag and tag not in tags:
                tags.append(tag)
    return tags


def get_fallback_metadata(error_message: str) -> Dict[str, Any]:
    """Return fallback metadata when analysis fails."""
    return {
        "description": f"Analysis failed: {error_message}",
        "tags": [],
        "character_types": [],
        "clothing": [],
        "body_features": [],
        "actions": [],
        "themes": [],
        "settings": [],
        "raw_keywords": [],
    }


def get_mock_metadata() -> Dict[str, Any]:
    """Return mock metadata for testing when VLM is not available."""
    import random

    character_types = ["loli", "catgirl", "teen"]
    clothing = ["school_uniform", "swimsuit"]
    body_features = ["large_breasts", "glasses"]
    themes = ["vanilla", "romance"]

    selected_chars = random.sample(character_types, min(2, len(character_types)))
    selected_clothing = random.sample(clothing, min(1, len(clothing)))
    selected_body = random.sample(body_features, min(1, len(body_features)))
    selected_themes = random.sample(themes, min(1, len(themes)))

    all_keywords = selected_chars + selected_clothing + selected_body + selected_themes

    return {
        "description": f"Mock analysis: {', '.join(all_keywords)}",
        "character_types": selected_chars,
        "clothing": selected_clothing,
        "body_features": selected_body,
        "actions": [],
        "themes": selected_themes,
        "settings": [],
        "raw_keywords": all_keywords,
    }
